### ISSUE TITLE
GEE Repo

### ISSUE THREAD

**Issue by Vematool** [msalinero/GEEGPRPhenoDemos#1]
https://code.earthengine.google.com/?accept_repo=users/msalinero85/GPRPhenologyDemos is not working. Kindly review

**Comment by msalinero** [comment]
Please try:
•	After accept to add the code in your GEE account, you should click the refresh button.
•	Then you should be able to see the code in the Reader section under the Scripts tab.

![image](https://user-images.githubusercontent.com/9076763/197709614-352a68be-169b-46f0-98d8-4676e97ab5b0.png)
